/**
 * Shared JSON-LD builders. One stable Organization @id is referenced from the
 * WebSite node and from every page's author/publisher, so search engines treat
 * the whole site as one entity (E-E-A-T / knowledge-graph signal).
 *
 * Vocabulary discipline: every type and property emitted from this file was
 * checked against the published schema.org vocabulary (schemaorg release
 * 29.1) — including its declared domain, which is why `lastReviewed` and
 * `reviewedBy` are attached to a WebPage node and never to the Article.
 */
import { site, absoluteUrl } from "@/lib/site";
import { termsDefining, termId } from "@/data/glossary";
import { PUBLISHED } from "@/data/published";
import type { ClusterEntry } from "@/lib/cluster";

export const ORG_ID = `${site.url}/#organization`;
export const WEBSITE_ID = `${site.url}/#website`;

/**
 * datePublished for a page, from the git-derived first-published map
 * (src/data/published.ts, generated by scripts/backfill-published.mjs).
 *
 * `key` is the URL path without its leading slash. A page newer than the last
 * regeneration has no row and falls back to `modified` — the same date every
 * page carried before the map existed, so a stale map degrades to the old
 * behaviour rather than to a guess.
 *
 * Clamped to never exceed `modified`. That is not hypothetical: an `updated`
 * stamp records when the facts were checked, and research can predate the
 * commit that ships it — 66 spokes were verified one to four days before
 * they were committed when the map was first generated. A datePublished after
 * dateModified is an inconsistency validators flag, and the two ways out are
 * not equal: moving dateModified forward would claim a re-verification that
 * never happened (the one number CLAUDE.md says must not be falsified), while
 * pulling datePublished back to the verification date only says the page's
 * content is as of the day it was checked — which is true.
 */
export function publishedDate(key: string, modified: string): string {
  const first = PUBLISHED[key] ?? modified;
  return first > modified ? modified : first;
}

/** Markdown mirror URL for a page path, per the llms.txt convention of
 *  serving the same URL with `.md` appended. */
export function markdownUrl(path: string): string {
  const clean = path.startsWith("/") ? path : `/${path}`;
  return absoluteUrl(clean === "/" ? "/index.md" : `${clean}.md`);
}

/** Subject areas the site claims expertise in — an entity signal, and a
 *  compact statement of scope for models building a topic profile. */
const KNOWS_ABOUT = [
  "Fitness APIs",
  "Wearable and health data integration",
  "Apple HealthKit",
  "Google Health Connect",
  "Health data aggregators",
  "AI motion tracking and pose estimation",
  "Nutrition APIs",
  "Health data compliance and privacy",
  "Bluetooth fitness devices",
  "Fitness app architecture",
];

/** The canonical Organization node. Emit once (in the root layout). */
export function organizationNode() {
  const sameAs = [site.social.github, site.social.twitter, site.social.linkedin].filter(
    Boolean,
  );
  return {
    "@type": "Organization",
    "@id": ORG_ID,
    name: site.name,
    url: site.url,
    description: site.description,
    knowsAbout: KNOWS_ABOUT,
    // Our sourcing and correction rules, published — the page a model should
    // read to decide how much to trust everything else here.
    publishingPrinciples: absoluteUrl("/methodology"),
    // Who pays for the site, in machine-readable form. The disclosure is
    // already in prose on /methodology and on every first-party page; this
    // states the same relationship where a crawler can read it without
    // parsing English (ops/GEO.md: never let the funding relationship be
    // something a reader has to infer).
    funder: {
      "@type": "Organization",
      name: "KinesteX",
      url: "https://kinestex.com",
    },
    ...(sameAs.length ? { sameAs } : {}),
  };
}

/**
 * The WebSite node's search action. Google's sitelinks-searchbox feature
 * needs a real results page behind it — /search is that page, and it works
 * without JavaScript's help from the URL alone, so the action is honest
 * rather than decorative.
 */
export function searchActionNode() {
  return {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: `${site.url}/search?q={search_term_string}`,
    },
    "query-input": "required name=search_term_string",
  };
}

/** A lightweight publisher/author reference to the Organization by @id. */
export function orgRef() {
  return { "@id": ORG_ID };
}

/** BreadcrumbList from an ordered list of {name, path}. path "" = home. */
export function breadcrumbNode(trail: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}

/**
 * Vendor and standards documentation: when an entry links one of these, the
 * link is evidence for a claim, so it is emitted as `citation`.
 */
const DOC_DOMAINS = [
  "developer.apple.com",
  "developers.google.com",
  "developer.android.com",
  "developers.strava.com",
  "dev.fitbit.com",
  "developer.garmin.com",
  "cloud.ouraring.com",
  "developer.whoop.com",
  "docs.tryterra.co",
  "bluetooth.com",
  "www.bluetooth.com",
  "w3.org",
  "www.w3.org",
  "developer.mozilla.org",
];

/**
 * Everything else we link on purpose — repositories, projects, tools — is
 * emitted as `mentions`, not `citation`.
 *
 * The distinction is deliberate and it matters: a page that recommends
 * WireMock is not *citing* WireMock, and a page whose repo links are the
 * evidence behind a claim cannot be told apart from one that merely name-drops
 * a tool by URL pattern alone. `mentions` is true in both cases; `citation`
 * would be a claim about evidentiary role we cannot make programmatically.
 * Inflating `citation` is the machine-readable version of padding a
 * bibliography, and this site does not do that in prose either.
 */
const MENTION_DOMAINS = ["github.com", "gitlab.com", "pypi.org", "www.npmjs.com", "npmjs.com"];

function externalLinks(body: string): string[] {
  const urls = new Set<string>();
  for (const m of body.matchAll(/\]\((https?:\/\/[^)\s]+)\)/g)) urls.add(m[1]);
  return [...urls];
}

function hostOf(url: string): string | null {
  try {
    return new URL(url).hostname;
  } catch {
    return null; // malformed URL in body — ignore rather than crash the build
  }
}

/** Vendor/standards documentation an entry links, as cited works. */
export function citationsFromBody(body: string): { "@type": string; url: string }[] {
  return externalLinks(body)
    .filter((u) => {
      const h = hostOf(u);
      return h !== null && DOC_DOMAINS.includes(h);
    })
    .map((url) => ({ "@type": "WebPage", url }));
}

/**
 * Identity key for a URL when deduplicating: the same page can be written
 * with escaped or literal parentheses (Apple's symbol URLs) and with or
 * without a trailing slash or fragment.
 */
function urlKey(url: string): string {
  try {
    const u = new URL(url);
    u.hash = "";
    return decodeURI(u.href).replace(/\/$/, "");
  } catch {
    return url;
  }
}

/**
 * Everything an entry cites: vendor/standards docs linked in the body, plus
 * every page in `entry.sources`. A recorded source is evidence by
 * construction — it is the page a re-verification checked the claims against
 * — so it is cited whatever its domain, which the body heuristic cannot do.
 * One node per page, body links first, in first-seen order.
 */
export function entryCitations(entry: Pick<ClusterEntry, "body" | "sources">) {
  const seen = new Set<string>();
  const out: { "@type": string; url: string }[] = [];
  const add = (url: string) => {
    const key = urlKey(url);
    if (seen.has(key)) return;
    seen.add(key);
    out.push({ "@type": "WebPage", url });
  };
  for (const c of citationsFromBody(entry.body)) add(c.url);
  for (const s of entry.sources ?? []) add(s.url);
  return out;
}

/** Projects, repositories and tools an entry links — mentioned, not cited. */
export function mentionsFromBody(body: string): { "@type": string; url: string }[] {
  return externalLinks(body)
    .filter((u) => {
      const h = hostOf(u);
      return h !== null && MENTION_DOMAINS.includes(h);
    })
    .map((url) => ({ "@type": "CreativeWork", url }));
}

/** Rough word count of an entry body, for `wordCount`. */
function wordCount(body: string): number {
  return body.split(/\s+/).filter(Boolean).length;
}

/**
 * The full JSON-LD graph for a cluster spoke: a TechArticle (the content),
 * a WebPage (the document, carrying review metadata), and — when the page is
 * the site's canonical explanation of a glossary concept — `about` links to
 * that concept's stable DefinedTerm @id.
 */
export function spokeGraph({
  entry,
  basePath,
  hubLabel,
  capsuleId = "answer",
}: {
  entry: ClusterEntry;
  basePath: string;
  hubLabel: string;
  capsuleId?: string;
}) {
  const path = `${basePath}/${entry.slug}`;
  const url = absoluteUrl(path);
  const pageId = `${url}#webpage`;
  const articleId = `${url}#article`;

  const defines = termsDefining(path);
  const about = defines.map((t) => ({
    "@type": "DefinedTerm",
    "@id": termId(t.term),
    name: t.term,
    description: t.def,
    inDefinedTermSet: absoluteUrl("/glossary"),
  }));
  const citation = entryCitations(entry);
  // A page cited as evidence is not also merely "mentioned".
  const cited = new Set(citation.map((c) => urlKey(c.url)));
  const mentions = mentionsFromBody(entry.body).filter((m) => !cited.has(urlKey(m.url)));

  // Cookbook pages are runnable recipes: mark the code as SoftwareSourceCode
  // so the SERP entry can widen and agents can tell "article with code" from
  // "article about code". Language read from the fences actually present.
  const fenceLangs = [...new Set([...entry.body.matchAll(/```([a-z]+)/g)].map((m) => m[1]))]
    .filter((l) => l !== "text" && l !== "bash");
  const sourceCode =
    basePath === "/cookbook" && fenceLangs.length
      ? {
          "@type": "SoftwareSourceCode",
          name: `${entry.h1} — reference implementation`,
          description: entry.metaDescription,
          programmingLanguage: fenceLangs,
          url: `${url}#code`,
          isPartOf: { "@id": articleId },
        }
      : null;

  // When the page's primary query is literally a question, expose it as a
  // schema.org Question with the answer capsule as acceptedAnswer. This is
  // deliberately NOT QAPage (that type is for forum-style pages and would be
  // an invalid rich-result claim); a Question node on the WebPage is valid
  // vocabulary and gives answer engines the pairing explicitly.
  const isQuestion = /^(what|how|why|which|when|where|can|do|does|is|are|should)\b/i.test(
    entry.primaryQuery,
  );
  const questionEntity = isQuestion
    ? {
        "@type": "Question",
        name: entry.primaryQuery.endsWith("?") ? entry.primaryQuery : `${entry.primaryQuery}?`,
        answerCount: 1,
        acceptedAnswer: { "@type": "Answer", text: entry.answer, url: `${url}#answer` },
      }
    : null;

  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "TechArticle",
        "@id": articleId,
        headline: entry.h1,
        alternativeHeadline: entry.primaryQuery,
        description: entry.metaDescription,
        abstract: entry.answer,
        // First commit that shipped this URL, not the last re-verification:
        // the `updated` stamp moves on every re-check, so using it here made
        // each re-verified page claim it was born on the day it was checked.
        datePublished: publishedDate(path.slice(1), entry.updated),
        dateModified: entry.updated,
        author: orgRef(),
        publisher: orgRef(),
        inLanguage: "en",
        articleSection: hubLabel,
        wordCount: wordCount(entry.body),
        isPartOf: { "@id": WEBSITE_ID },
        mainEntityOfPage: { "@id": pageId },
        url,
        speakable: {
          "@type": "SpeakableSpecification",
          cssSelector: [`#${capsuleId}`],
        },
        ...(about.length ? { about } : {}),
        ...(citation.length ? { citation } : {}),
        ...(mentions.length ? { mentions } : {}),
      },
      {
        // `lastReviewed` and `reviewedBy` are WebPage properties in the
        // schema.org vocabulary, so they live here rather than on the article.
        "@type": "WebPage",
        "@id": pageId,
        url,
        name: entry.h1,
        isPartOf: { "@id": WEBSITE_ID },
        lastReviewed: entry.updated,
        reviewedBy: orgRef(),
        primaryImageOfPage: { "@type": "ImageObject", url: `${url}/opengraph-image` },
        // The markdown mirror of this page, for clients that prefer it.
        encoding: {
          "@type": "MediaObject",
          encodingFormat: "text/markdown",
          contentUrl: markdownUrl(path),
        },
        ...(questionEntity ? { mainEntity: questionEntity } : {}),
      },
      ...(sourceCode ? [sourceCode] : []),
    ],
  };
}

/**
 * The JSON-LD graph for a blog post: one Article node and its WebPage.
 *
 * A post is a TechArticle in the same sense a spoke is — technical reference
 * writing, not a diary — and it is also a BlogPosting. Those used to be two
 * separate nodes on the page, which told a crawler there were two articles at
 * one URL with two different authors (one by @id, one an inline copy of the
 * Organization). They are one thing, so they are one node carrying both
 * types: every property either type contributes lives on it once.
 *
 * `image` is the post's own share image — its cover when it has one,
 * otherwise the co-located opengraph-image card — so the structured data
 * names the same picture og:image does.
 */
export function postGraph({
  slug,
  title,
  description,
  published,
  updated,
  author,
  tags,
  words,
  image,
  capsuleId = "answer",
}: {
  slug: string;
  title: string;
  description: string;
  published: string;
  updated: string;
  author: string;
  tags: string[];
  words: number;
  /** Absolute URL; width/height only when known (the generated card). */
  image: { url: string; width?: number; height?: number };
  capsuleId?: string;
}) {
  const path = `/blog/${slug}`;
  const url = absoluteUrl(path);
  const pageId = `${url}#webpage`;
  const imageNode = { "@type": "ImageObject", ...image };
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": ["BlogPosting", "TechArticle"],
        "@id": `${url}#article`,
        headline: title,
        description,
        // Frontmatter `date` is the post's declared publish date (it matched
        // the commit that added the file for every post when
        // src/data/published.ts was first generated). Clamped the same way
        // spokes are, so a frontmatter `updated` earlier than `date` cannot
        // produce a publish date after the modification date.
        datePublished: published > updated ? updated : published,
        dateModified: updated,
        // Posts by the site resolve to the one Organization entity by @id;
        // a named human author stays a Person, since no Person entity with a
        // stable @id exists to reference.
        author: author === site.name ? orgRef() : { "@type": "Person", name: author },
        publisher: orgRef(),
        image: imageNode,
        inLanguage: "en",
        articleSection: "Blog",
        wordCount: words,
        keywords: tags.join(", "),
        isPartOf: { "@id": WEBSITE_ID },
        mainEntityOfPage: { "@id": pageId },
        url,
        speakable: {
          "@type": "SpeakableSpecification",
          cssSelector: [`#${capsuleId}`],
        },
      },
      {
        "@type": "WebPage",
        "@id": pageId,
        url,
        name: title,
        isPartOf: { "@id": WEBSITE_ID },
        lastReviewed: updated,
        reviewedBy: orgRef(),
        primaryImageOfPage: imageNode,
        encoding: {
          "@type": "MediaObject",
          encodingFormat: "text/markdown",
          contentUrl: markdownUrl(path),
        },
      },
    ],
  };
}

/**
 * The JSON-LD graph for a /tools page: a WebApplication (the tool) and,
 * unless the page already emits one, the WebPage it lives on.
 *
 * Every tool used to be typed TechArticle except the stack generator, which
 * was a WebApplication — the same kind of page described two ways. A tool is
 * software a reader operates, not prose they read, so all six are
 * WebApplications now (WebApplication → SoftwareApplication → CreativeWork,
 * so the CreativeWork properties the pages already set still apply).
 * `articleSection` is Article-only and goes with the type change; `speakable`
 * is declared on Article and WebPage only, and `lastReviewed`, `reviewedBy`
 * and `primaryImageOfPage` on WebPage only, so all four live on the WebPage
 * node — the same split spokeGraph makes for the same vocabulary reason.
 * Domains checked against the schemaorg vocabulary (data/schema.ttl).
 *
 * Dates are passed through as each page already stated them; this builder
 * adds none. `datePublished` stays absent on a tool that never declared one.
 */
export function toolGraph({
  path,
  name,
  description,
  alternativeHeadline,
  dateModified,
  datePublished,
  webPage,
  capsuleId = "answer",
}: {
  path: string;
  name: string;
  description: string;
  alternativeHeadline?: string;
  dateModified: string;
  datePublished?: string;
  /**
   * The WebPage node, with the date the facts the tool answers from were last
   * checked. Omit it when the page renders <PageSummary>, which emits the
   * same #webpage node itself — two copies would have to be kept in step.
   */
  webPage?: { lastReviewed: string };
  capsuleId?: string;
}) {
  const url = absoluteUrl(path);
  const pageId = `${url}#webpage`;
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebApplication",
        "@id": `${url}#app`,
        name,
        ...(alternativeHeadline ? { alternativeHeadline } : {}),
        description,
        url,
        applicationCategory: "DeveloperApplication",
        // Matches the value the stack generator already declared: these run
        // in any browser, with no install.
        operatingSystem: "Web",
        isAccessibleForFree: true,
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        ...(datePublished ? { datePublished } : {}),
        dateModified,
        author: orgRef(),
        publisher: orgRef(),
        inLanguage: "en",
        isPartOf: { "@id": WEBSITE_ID },
        mainEntityOfPage: { "@id": pageId },
      },
      ...(webPage
        ? [
            {
              "@type": "WebPage",
              "@id": pageId,
              url,
              name,
              isPartOf: { "@id": WEBSITE_ID },
              lastReviewed: webPage.lastReviewed,
              reviewedBy: orgRef(),
              primaryImageOfPage: { "@type": "ImageObject", url: absoluteUrl("/opengraph-image") },
              speakable: { "@type": "SpeakableSpecification", cssSelector: [`#${capsuleId}`] },
            },
          ]
        : []),
    ],
  };
}

/**
 * CollectionPage + ItemList for a cluster hub: states that this URL is a
 * curated collection and enumerates its members in order, so a model reading
 * one hub learns the whole cluster without crawling it.
 */
export function hubGraph({
  basePath,
  name,
  description,
  updated,
  entries,
  capsuleId = "answer",
}: {
  basePath: string;
  name: string;
  description: string;
  updated: string;
  entries: { slug: string; h1: string; metaDescription: string }[];
  capsuleId?: string;
}) {
  const url = absoluteUrl(basePath);
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "@id": `${url}#collection`,
    url,
    name,
    description,
    inLanguage: "en",
    isPartOf: { "@id": WEBSITE_ID },
    publisher: orgRef(),
    lastReviewed: updated,
    reviewedBy: orgRef(),
    speakable: { "@type": "SpeakableSpecification", cssSelector: [`#${capsuleId}`] },
    encoding: {
      "@type": "MediaObject",
      encodingFormat: "text/markdown",
      contentUrl: markdownUrl(basePath),
    },
    mainEntity: {
      "@type": "ItemList",
      numberOfItems: entries.length,
      itemListOrder: "https://schema.org/ItemListOrderAscending",
      itemListElement: entries.map((e, i) => ({
        "@type": "ListItem",
        position: i + 1,
        name: e.h1,
        description: e.metaDescription,
        url: absoluteUrl(`${basePath}/${e.slug}`),
      })),
    },
  };
}
