import type { MetadataRoute } from "next";
import { site } from "@/lib/site";

/**
 * Web app manifest. Not because this is an app — it is a reading site — but
 * because "add to home screen" and the browser's install/shortcut UI look at
 * this file for the name, colours and icon, and without it a saved bookmark
 * gets the bare hostname and a screenshot of the page as its tile.
 *
 * Everything here restates what already exists elsewhere, deliberately sourced
 * rather than retyped: names and description come from `src/lib/site.ts` (the
 * single source of truth the metadata, sitemap and RSS all read), and the
 * colours are the light-theme values from `layout.tsx`'s viewport export — the
 * manifest has no media-query form, so it takes the light scheme and the
 * `themeColor` pair keeps handling the dark one.
 *
 * Icons are the two that exist: the static SVG favicon and the generated
 * 180×180 apple-touch PNG. No sizes are claimed that no file can serve.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: site.title,
    short_name: site.name,
    description: site.description,
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#ffffff",
    categories: ["education", "health", "fitness"],
    icons: [
      {
        // Scalable, so one file answers every size a launcher asks for.
        src: "/icon.svg",
        type: "image/svg+xml",
        sizes: "any",
        purpose: "any",
      },
      {
        // Generated by src/app/apple-icon.tsx; iOS ignores SVG favicons and
        // needs this raster tile.
        src: "/apple-icon",
        type: "image/png",
        sizes: "180x180",
        purpose: "any",
      },
    ],
  };
}
